name: Cypress CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  cypress-tests:
    
    runs-on: windows-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run Cypress tests
      - name: Run Cypress tests
        run: npx cypress run --browser edge
      # Archive Cypress artifacts (screenshots/videos)
      - name: Archive test artifacts
        if: always() # Ensure this step runs even if tests fail
        uses: actions/upload-artifact@v3
        with:
          name: cypress-artifacts
          path: cypress/screenshots,cypress/videos

      # Generate Cypress report using Mochawesome
      - name: Generate Cypress Report
        run: |
          npx cypress run --reporter mochawesome --reporter-options overwrite=false,html=true,json=true

      # Archive Cypress HTML report
      - name: Upload HTML Report
        uses: actions/upload-artifact@v3
        with:
          name: cypress-report
          path: mochawesome-report/mochawesome.html